Реализация команды изменения линейной скорости
chemakin-aleksandr/otus-main-patterns-2022-11 pull request #5
Opened 2022-12-19 17:32 UTC by 71andy

2022-12-19 18:12 UTC, vakhet requested changes

2022-12-19 18:12 UTC, vakhet commented on space_invaders/engine/commands/change_linear_velocity.py
> +from space_invaders.engine.interfaces.linear_velocity_controller import (
для упрощения импорта можно все интерфейсы добавить в interfaces/__init__.py атрибут __all__ = (...)

2022-12-19 18:12 UTC, vakhet commented on space_invaders/engine/exceptions.py
> +    """"""
пустой докстринг

2022-12-21 06:20 UTC, 71andy commented on space_invaders/engine/exceptions.py
> +    """"""
описание исключения добавил

2022-12-21 06:30 UTC, 71andy commented on space_invaders/engine/commands/change_linear_velocity.py
> +from space_invaders.engine.interfaces.linear_velocity_controller import (
поправил

2022-12-21 06:53 UTC, vakhet approved these changes

2022-12-23 21:51 UTC, a-poliakov reviewed
помимо команды движения объекта еще можно реализовать поворот объекта

2023-01-16 09:51 UTC, vakhet approved these changes

2023-01-24 11:56 UTC, merged